#!/usr/bin/env python3
"""
CMB Power Spectrum Analysis
============================

This script analyzes the CMB power spectrum generated by CAMB and verifies
that our flat-sky CMB map generation produces the expected power spectrum
with baryon acoustic oscillations (BAO) and other expected features.

Key features checked:
- D_ℓ = ℓ(ℓ+1)C_ℓ/(2π) power spectrum shape
- Acoustic peaks at ℓ ≈ 220, 540, 810, ...
- Silk damping at high ℓ
- Comparison of lensed vs unlensed spectra
- Verification of flat-sky map power spectrum recovery
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import camb
from scipy.integrate import quad

# ============================================================================
# CONFIGURATION
# ============================================================================

# Cosmological parameters (Planck 2018)
H0_KM_S_MPC = 67.4
OMEGA_M0 = 0.315
OMEGA_L0 = 0.685
OMEGA_B0 = 0.0493

# Output directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "plots_grizzly/")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================================
# CMB POWER SPECTRUM FUNCTIONS
# ============================================================================

def get_cmb_power_spectra(lmax=5000):
    """
    Get CMB power spectra from CAMB.
    
    Returns D_ℓ = ℓ(ℓ+1)C_ℓ/(2π) in µK² for both lensed and unlensed.
    """
    print("Computing CMB power spectra with CAMB...")
    
    # Set up CAMB parameters
    pars = camb.set_params(
        H0=H0_KM_S_MPC,
        ombh2=OMEGA_B0 * (H0_KM_S_MPC/100)**2,
        omch2=(OMEGA_M0 - OMEGA_B0) * (H0_KM_S_MPC/100)**2,
        tau=0.054,
        As=2.1e-9,
        ns=0.965,
        lmax=lmax,
        lens_potential_accuracy=1
    )
    
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit='muK')
    
    # Extract spectra (CAMB returns D_ℓ directly)
    ells = np.arange(powers['total'].shape[0])
    
    # TT is first column (index 0)
    Dl_lensed = powers['total'][:, 0]
    Dl_unlensed = powers['unlensed_scalar'][:, 0]
    
    # Also get EE, TE for completeness
    Dl_EE_lensed = powers['total'][:, 1]
    Dl_TE_lensed = powers['total'][:, 3]
    
    print(f"  Computed spectra up to ℓ = {lmax}")
    print(f"  Peak D_ℓ(TT) ≈ {Dl_lensed.max():.1f} µK² at ℓ ≈ {ells[np.argmax(Dl_lensed)]}")
    
    return {
        'ells': ells,
        'Dl_TT_lensed': Dl_lensed,
        'Dl_TT_unlensed': Dl_unlensed,
        'Dl_EE_lensed': Dl_EE_lensed,
        'Dl_TE_lensed': Dl_TE_lensed,
    }


def compute_comoving_distance(z):
    """Compute comoving distance to redshift z in Mpc."""
    c_km_s = 299792.458
    
    def E(zp):
        return np.sqrt(OMEGA_M0 * (1 + zp)**3 + OMEGA_L0)
    
    chi_integral, _ = quad(lambda zp: 1.0 / E(zp), 0, z)
    chi_Mpc = (c_km_s / H0_KM_S_MPC) * chi_integral
    
    return chi_Mpc


def generate_flat_sky_cmb(nx, ny, Lx_Mpc, Ly_Mpc, z_mean, lensed=True, seed=42):
    """
    Generate a flat-sky CMB temperature anisotropy map.
    
    Parameters:
    -----------
    nx, ny : int
        Number of pixels in x and y directions
    Lx_Mpc, Ly_Mpc : float
        Physical box size in Mpc (not Mpc/h)
    z_mean : float
        Mean redshift (for angular diameter distance)
    lensed : bool
        Use lensed or unlensed C_ℓ
    seed : int
        Random seed
        
    Returns:
    --------
    cmb_map : ndarray (ny, nx)
        CMB temperature map in µK
    """
    np.random.seed(seed)
    
    # Comoving distance
    chi_Mpc = compute_comoving_distance(z_mean)
    
    # Angular size of box in radians
    theta_x = Lx_Mpc / chi_Mpc
    theta_y = Ly_Mpc / chi_Mpc
    
    # Pixel size in radians
    dx_rad = theta_x / nx
    dy_rad = theta_y / ny
    
    # Get C_ℓ from CAMB
    ell_max = int(np.pi / min(dx_rad, dy_rad)) + 100
    ell_max = min(ell_max, 15000)
    
    # Get power spectrum
    pars = camb.set_params(
        H0=H0_KM_S_MPC,
        ombh2=OMEGA_B0 * (H0_KM_S_MPC/100)**2,
        omch2=(OMEGA_M0 - OMEGA_B0) * (H0_KM_S_MPC/100)**2,
        tau=0.054,
        As=2.1e-9,
        ns=0.965,
        lmax=ell_max,
        lens_potential_accuracy=1 if lensed else 0
    )
    
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit='muK')
    
    if lensed:
        Dl_raw = powers['total'][:, 0]
    else:
        Dl_raw = powers['unlensed_scalar'][:, 0]
    
    # Convert D_ℓ to C_ℓ
    ells = np.arange(len(Dl_raw))
    Cl_TT = np.zeros_like(Dl_raw)
    Cl_TT[2:] = Dl_raw[2:] * 2 * np.pi / (ells[2:] * (ells[2:] + 1))
    
    # Create 2D k-space grid
    kx = 2 * np.pi * np.fft.fftfreq(ny, d=dy_rad)
    ky = 2 * np.pi * np.fft.fftfreq(nx, d=dx_rad)
    KX, KY = np.meshgrid(ky, kx)
    ell_2d = np.sqrt(KX**2 + KY**2)
    
    # Interpolate C_ℓ to 2D grid
    Cl_2d = np.interp(ell_2d, ells, Cl_TT, left=0, right=0)
    
    # Generate Gaussian random field in Fourier space
    # Area in steradians
    area_sr = theta_x * theta_y
    
    # Power spectrum amplitude for FFT normalization
    # This matches the normalization in analysis_with_cmb.py
    amplitude = np.sqrt(Cl_2d * (2 * np.pi)**2 / area_sr / 2)
    
    # Generate complex Gaussian random field
    real_part = np.random.randn(ny, nx)
    imag_part = np.random.randn(ny, nx)
    cmb_fourier = amplitude * (real_part + 1j * imag_part)
    
    # Inverse FFT
    cmb_map = np.real(np.fft.ifft2(cmb_fourier)) * (ny * nx)
    
    # Enforce zero mean
    cmb_map -= cmb_map.mean()
    
    return cmb_map, chi_Mpc, theta_x, theta_y


def measure_map_power_spectrum(cmb_map, theta_x, theta_y, n_bins=100):
    """
    Measure the power spectrum of a flat-sky CMB map.
    
    Returns D_ℓ = ℓ(ℓ+1)C_ℓ/(2π) in µK².
    """
    ny, nx = cmb_map.shape
    
    # Pixel sizes in radians
    dx_rad = theta_x / nx
    dy_rad = theta_y / ny
    
    # Area in steradians
    area_sr = theta_x * theta_y
    
    # FFT (matching the inverse normalization used in generation)
    cmb_fft = np.fft.fft2(cmb_map) / (nx * ny)
    
    # Power spectrum: |FFT|² * area / (2π)²
    # This inverts the normalization: amplitude = sqrt(C_ℓ * (2π)² / area / 2)
    # So |amplitude|² = C_ℓ * (2π)² / area / 2
    # And |FFT|² = |amplitude|² * 2 (from real+imag parts)
    # Therefore C_ℓ = |FFT|² * area / (2π)²
    power_2d = np.abs(cmb_fft)**2 * area_sr / (2 * np.pi)**2 * 2
    
    # Create ℓ grid
    kx = 2 * np.pi * np.fft.fftfreq(ny, d=dy_rad)
    ky = 2 * np.pi * np.fft.fftfreq(nx, d=dx_rad)
    KX, KY = np.meshgrid(ky, kx)
    ell_2d = np.sqrt(KX**2 + KY**2)
    
    # Bin the power spectrum
    ell_max = ell_2d.max()
    ell_bins = np.linspace(0, ell_max, n_bins + 1)
    ell_centers = 0.5 * (ell_bins[:-1] + ell_bins[1:])
    
    Cl_binned = np.zeros(n_bins)
    counts = np.zeros(n_bins)
    
    for i in range(n_bins):
        mask = (ell_2d >= ell_bins[i]) & (ell_2d < ell_bins[i+1])
        if np.any(mask):
            Cl_binned[i] = np.mean(power_2d[mask])
            counts[i] = np.sum(mask)
    
    # Convert C_ℓ to D_ℓ
    Dl_binned = ell_centers * (ell_centers + 1) * Cl_binned / (2 * np.pi)
    
    # Only return bins with data
    valid = counts > 0
    
    return ell_centers[valid], Dl_binned[valid], Cl_binned[valid]


# ============================================================================
# MAIN ANALYSIS
# ============================================================================

def main():
    print("="*80)
    print("CMB POWER SPECTRUM ANALYSIS")
    print("="*80)
    
    # =========================================================================
    # 1. Get theoretical power spectra from CAMB
    # =========================================================================
    spectra = get_cmb_power_spectra(lmax=5000)
    ells = spectra['ells']
    Dl_lensed = spectra['Dl_TT_lensed']
    Dl_unlensed = spectra['Dl_TT_unlensed']
    
    # =========================================================================
    # 2. Plot theoretical CMB TT power spectrum
    # =========================================================================
    print("\nPlotting theoretical CMB power spectrum...")
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    # Panel (0,0): Full D_ℓ spectrum (linear scale)
    ax = axes[0, 0]
    ax.plot(ells, Dl_lensed, 'b-', linewidth=1.5, label='Lensed')
    ax.plot(ells, Dl_unlensed, 'r--', linewidth=1.5, label='Unlensed')
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell = \\ell(\\ell+1)C_\\ell/2\\pi$ [µK²]', fontsize=14)
    ax.set_title('CMB TT Power Spectrum', fontweight='bold', fontsize=14)
    ax.legend(fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, 3000])
    ax.set_ylim([0, 7000])
    
    # Mark acoustic peaks
    peak_positions = [220, 540, 810, 1120, 1450]
    for i, peak in enumerate(peak_positions):
        if peak < 3000:
            ax.axvline(x=peak, color='gray', linestyle=':', alpha=0.5)
            ax.text(peak, 6500 - i*500, f'ℓ≈{peak}', fontsize=9, ha='center')
    
    # Panel (0,1): Zoom on first acoustic peak
    ax = axes[0, 1]
    mask = (ells >= 100) & (ells <= 400)
    ax.plot(ells[mask], Dl_lensed[mask], 'b-', linewidth=2, label='Lensed')
    ax.plot(ells[mask], Dl_unlensed[mask], 'r--', linewidth=2, label='Unlensed')
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell$ [µK²]', fontsize=14)
    ax.set_title('First Acoustic Peak (ℓ ≈ 220)', fontweight='bold', fontsize=14)
    ax.legend(fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.axvline(x=220, color='purple', linestyle='--', alpha=0.7, label='ℓ=220')
    
    # Panel (1,0): High-ℓ damping tail
    ax = axes[1, 0]
    mask = (ells >= 1000) & (ells <= 5000)
    ax.plot(ells[mask], Dl_lensed[mask], 'b-', linewidth=1.5, label='Lensed')
    ax.plot(ells[mask], Dl_unlensed[mask], 'r--', linewidth=1.5, label='Unlensed')
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell$ [µK²]', fontsize=14)
    ax.set_title('Silk Damping Tail', fontweight='bold', fontsize=14)
    ax.legend(fontsize=12)
    ax.grid(True, alpha=0.3)
    
    # Panel (1,1): Log scale to see full dynamic range
    ax = axes[1, 1]
    mask = ells >= 2
    ax.loglog(ells[mask], Dl_lensed[mask], 'b-', linewidth=1.5, label='Lensed')
    ax.loglog(ells[mask], Dl_unlensed[mask], 'r--', linewidth=1.5, label='Unlensed')
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell$ [µK²]', fontsize=14)
    ax.set_title('Full Spectrum (log-log)', fontweight='bold', fontsize=14)
    ax.legend(fontsize=12)
    ax.grid(True, alpha=0.3, which='both')
    
    plt.suptitle('Theoretical CMB Power Spectrum from CAMB', fontsize=16, fontweight='bold')
    plt.tight_layout()
    outfile = os.path.join(OUTPUT_DIR, 'cmb_power_spectrum_theory.png')
    plt.savefig(outfile, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {outfile}")
    
    # =========================================================================
    # 3. Generate flat-sky CMB map and verify power spectrum recovery
    # =========================================================================
    print("\nGenerating flat-sky CMB maps...")
    
    # Case 1: Small box (like kSZ analysis) - can't resolve BAOs
    z_mean = 8.0
    box_Mpc_small = 500.0 / 0.7  # 500 Mpc/h -> Mpc
    nx, ny = 540, 540
    
    cmb_map_small, chi_Mpc, theta_x_small, theta_y_small = generate_flat_sky_cmb(
        nx, ny, box_Mpc_small, box_Mpc_small, z_mean, lensed=True, seed=42
    )
    
    ell_min_small = 2 * np.pi / theta_x_small
    print(f"\n  SMALL BOX (kSZ-like):")
    print(f"    Box size: {box_Mpc_small:.1f} Mpc at z={z_mean}")
    print(f"    Angular size: {np.degrees(theta_x_small):.2f}° ({np.degrees(theta_x_small)*60:.0f} arcmin)")
    print(f"    ℓ_min ≈ {ell_min_small:.0f} (CANNOT resolve first peak at ℓ≈220!)")
    print(f"    Map RMS: {cmb_map_small.std():.1f} µK")
    
    # Case 2: Large box - CAN resolve BAOs
    # Need θ > 2π/220 ≈ 1.6° minimum, use 30° to see multiple peaks
    box_Mpc_large = 30000.0  # 30 Gpc - very large box
    nx_large, ny_large = 1024, 1024
    
    cmb_map_large, _, theta_x_large, theta_y_large = generate_flat_sky_cmb(
        nx_large, ny_large, box_Mpc_large, box_Mpc_large, z_mean, lensed=True, seed=42
    )
    
    ell_min_large = 2 * np.pi / theta_x_large
    print(f"\n  LARGE BOX (BAO-resolving):")
    print(f"    Box size: {box_Mpc_large:.1f} Mpc at z={z_mean}")
    print(f"    Angular size: {np.degrees(theta_x_large):.1f}°")
    print(f"    ℓ_min ≈ {ell_min_large:.0f} (CAN resolve acoustic peaks!)")
    print(f"    Map RMS: {cmb_map_large.std():.1f} µK")
    
    # Measure power spectra
    ell_meas_small, Dl_meas_small, _ = measure_map_power_spectrum(
        cmb_map_small, theta_x_small, theta_y_small, n_bins=100
    )
    ell_meas_large, Dl_meas_large, _ = measure_map_power_spectrum(
        cmb_map_large, theta_x_large, theta_y_large, n_bins=150
    )
    
    # For backward compatibility
    cmb_map = cmb_map_small
    theta_x, theta_y = theta_x_small, theta_y_small
    ell_measured, Dl_measured = ell_meas_small, Dl_meas_small
    
    # =========================================================================
    # 4. Plot: Small box vs Large box comparison
    # =========================================================================
    print("\nPlotting CMB maps and power spectrum comparison...")
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    
    # Panel (0,0): Small box CMB map
    ax = axes[0, 0]
    vmax = 3 * cmb_map_small.std()
    im = ax.imshow(cmb_map_small, origin='lower', cmap='RdBu_r', vmin=-vmax, vmax=vmax)
    ax.set_title(f'Small Box: {np.degrees(theta_x_small):.1f}° ({np.degrees(theta_x_small)*60:.0f} arcmin)\n'
                 f'ℓ_min ≈ {ell_min_small:.0f} - CANNOT see BAOs', 
                 fontweight='bold', fontsize=12)
    plt.colorbar(im, ax=ax, label='µK')
    
    # Panel (0,1): Large box CMB map
    ax = axes[0, 1]
    vmax = 3 * cmb_map_large.std()
    im = ax.imshow(cmb_map_large, origin='lower', cmap='RdBu_r', vmin=-vmax, vmax=vmax)
    ax.set_title(f'Large Box: {np.degrees(theta_x_large):.1f}°\n'
                 f'ℓ_min ≈ {ell_min_large:.0f} - CAN see BAOs', 
                 fontweight='bold', fontsize=12)
    plt.colorbar(im, ax=ax, label='µK')
    
    # Panel (1,0): Power spectrum - small box (high ℓ only)
    ax = axes[1, 0]
    # Theory
    mask_theory = (ells >= 50) & (ells <= 4000)
    ax.plot(ells[mask_theory], Dl_lensed[mask_theory], 'b-', linewidth=2, 
            label='Theory (CAMB)', alpha=0.8)
    # Measured from small box
    mask_small = (ell_meas_small >= 50) & (ell_meas_small <= 4000)
    ax.plot(ell_meas_small[mask_small], Dl_meas_small[mask_small], 'ro', markersize=4, 
            alpha=0.6, label=f'Small box (ℓ_min≈{ell_min_small:.0f})')
    
    # Mark ℓ_min for small box
    ax.axvline(x=ell_min_small, color='red', linestyle='--', linewidth=2, alpha=0.7,
               label=f'ℓ_min (small box)')
    
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell$ [µK²]', fontsize=14)
    ax.set_title('Small Box: Misses Acoustic Peaks', fontweight='bold', fontsize=12)
    ax.legend(fontsize=10, loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, 3000])
    ax.set_ylim([0, 7000])
    
    # Mark acoustic peaks
    for peak in [220, 540, 810]:
        ax.axvline(x=peak, color='gray', linestyle=':', alpha=0.5)
    
    # Panel (1,1): Power spectrum - large box (shows BAOs!)
    ax = axes[1, 1]
    # Theory
    ax.plot(ells[mask_theory], Dl_lensed[mask_theory], 'b-', linewidth=2, 
            label='Theory (CAMB)', alpha=0.8)
    # Measured from large box
    mask_large = (ell_meas_large >= 10) & (ell_meas_large <= 3000)
    ax.plot(ell_meas_large[mask_large], Dl_meas_large[mask_large], 'go', markersize=4, 
            alpha=0.6, label=f'Large box (ℓ_min≈{ell_min_large:.0f})')
    
    # Mark ℓ_min for large box
    ax.axvline(x=ell_min_large, color='green', linestyle='--', linewidth=2, alpha=0.7,
               label=f'ℓ_min (large box)')
    
    ax.set_xlabel('Multipole ℓ', fontsize=14)
    ax.set_ylabel('$D_\\ell$ [µK²]', fontsize=14)
    ax.set_title('Large Box: Recovers Acoustic Peaks!', fontweight='bold', fontsize=12)
    ax.legend(fontsize=10, loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, 3000])
    ax.set_ylim([0, 7000])
    
    # Mark acoustic peaks
    for i, peak in enumerate([220, 540, 810]):
        ax.axvline(x=peak, color='purple', linestyle=':', alpha=0.7)
        ax.text(peak+20, 6000-i*800, f'ℓ≈{peak}', fontsize=10, color='purple')
    
    plt.suptitle('Why Small Boxes Cannot Resolve BAO Acoustic Peaks\n'
                 'Angular size determines minimum accessible multipole ℓ_min ≈ 2π/θ_box',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    outfile = os.path.join(OUTPUT_DIR, 'cmb_bao_resolution_comparison.png')
    plt.savefig(outfile, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {outfile}")
    
    # =========================================================================
    # 5. Print summary
    # =========================================================================
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    
    # Find acoustic peaks
    print("\nAcoustic Peak Positions (from CAMB):")
    for i, peak_ell in enumerate([220, 540, 810, 1120, 1450]):
        if peak_ell < len(Dl_lensed):
            print(f"  Peak {i+1}: ℓ ≈ {peak_ell}, D_ℓ ≈ {Dl_lensed[peak_ell]:.1f} µK²")
    
    print("\n" + "-"*60)
    print("BAO RESOLUTION ANALYSIS:")
    print("-"*60)
    print(f"\n  Your kSZ simulation box:")
    print(f"    Physical size: 500 Mpc/h = {box_Mpc_small:.1f} Mpc at z = {z_mean}")
    print(f"    Comoving distance: χ(z={z_mean}) = {chi_Mpc:.0f} Mpc")
    print(f"    Angular size: θ = L/χ = {np.degrees(theta_x_small):.2f}° = {np.degrees(theta_x_small)*60:.0f} arcmin")
    print(f"    Minimum ℓ: ℓ_min ≈ 2π/θ = {ell_min_small:.0f}")
    
    print(f"\n  Acoustic peak accessibility:")
    print(f"    Peak 1 (ℓ≈220): {'YES ✓' if ell_min_small < 220 else 'NO ✗'} (ℓ_min={ell_min_small:.0f} < 220)")
    print(f"    Peak 2 (ℓ≈540): {'YES ✓' if ell_min_small < 540 else 'NO ✗'}")
    print(f"    Peak 3 (ℓ≈810): {'YES ✓' if ell_min_small < 810 else 'NO ✗'}")
    
    # Number of modes at each peak
    n_modes_220 = int((220 / ell_min_small)**2) if ell_min_small < 220 else 0
    n_modes_540 = int((540 / ell_min_small)**2) if ell_min_small < 540 else 0
    print(f"\n  BUT: Cosmic variance limits precision!")
    print(f"    Modes at ℓ=220: ~{n_modes_220} (very noisy)")
    print(f"    Modes at ℓ=540: ~{n_modes_540}")
    print(f"    Need many modes to see clear oscillations")
    
    print(f"\n  Large box comparison ({np.degrees(theta_x_large):.0f}°):")
    print(f"    Minimum ℓ: ℓ_min ≈ {ell_min_large:.0f}")
    n_modes_220_large = int((220 / max(ell_min_large, 1))**2)
    print(f"    Modes at ℓ=220: ~{n_modes_220_large} (much better sampling!)")
    
    print("\n" + "="*80)
    print("CONCLUSION: Your box CAN technically access ℓ=220, but with only")
    print(f"~{n_modes_220} modes you get high cosmic variance. The measured spectrum")
    print("will be noisy and won't show clean BAO oscillations.")
    print("="*80)


if __name__ == "__main__":
    main()
